#!/bin/sh

cd "$HOME"

echo '- Installing/upgrading tmux plugins'
~/.tmux/plugins/tpm/bin/update_plugins all

echo "- Installing vim-plug"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &> /dev/null

echo "- Installing/updating neovim plugins"
nvim --headless +PlugUpdate +q +q &> /dev/null
